# Generated by Django 4.2.10 on 2024-02-08 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_invitation_to_user_alter_invitation_to_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
