# Generated by Django 4.2.11 on 2024-05-21 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('status_ready', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tournoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('max_players', models.IntegerField(blank=True, default=16)),
                ('start_datetime', models.DateTimeField(null=True)),
                ('admin_id', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_1_score', models.IntegerField(null=True)),
                ('player_2_score', models.IntegerField(null=True)),
                ('tour', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=0)),
                ('leave', models.IntegerField(default=0)),
                ('match_id', models.IntegerField(default=1)),
                ('game_id', models.IntegerField(blank=True, null=True)),
                ('player_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='apiTournament.joueur')),
                ('player_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to='apiTournament.joueur')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='apiTournament.tournoi')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to='apiTournament.joueur')),
            ],
        ),
        migrations.AddField(
            model_name='joueur',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='apiTournament.tournoi'),
        ),
    ]
