# Generated by Django 4.2.11 on 2024-03-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiTournament', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournoi',
            name='matchs',
        ),
    ]
