# Generated by Django 4.2.11 on 2024-03-28 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiTournament', '0002_remove_tournoi_matchs'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='apiTournament.tournoi'),
        ),
    ]
