# Generated by Django 4.2.11 on 2024-03-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTournament', '0003_joueur_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournoi',
            name='admin_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
