# Generated by Django 4.2.11 on 2024-04-16 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiTournament', '0004_tournoi_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='status_ready',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='apiTournament.tournoi'),
        ),
    ]
