# Generated by Django 4.2.11 on 2024-04-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiTournament', '0005_joueur_status_ready_match_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_id',
        ),
    ]
