# Generated by Django 4.2.11 on 2024-04-16 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiTournament', '0006_remove_match_match_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='apiTournament.joueur'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to='apiTournament.joueur'),
        ),
    ]
