# Generated by Django 4.2.11 on 2024-04-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTournament', '0007_alter_match_player_1_alter_match_player_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_id',
            field=models.IntegerField(default=1),
        ),
    ]
