# Generated by Django 4.2.11 on 2024-04-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTournament', '0008_match_match_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournoi',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
