# Generated by Django 4.2.11 on 2024-04-30 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiTournament', '0009_alter_tournoi_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='apiTournament.tournoi'),
        ),
    ]
