# Generated by Django 4.2.11 on 2024-05-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTournament', '0010_alter_joueur_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='leave',
            field=models.IntegerField(default=0),
        ),
    ]
