# Generated by Django 4.2.11 on 2024-05-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiTournament', '0011_match_game_id'),
        ('apiTournament', '0011_match_leave'),
    ]

    operations = [
    ]
