# build
FROM node:18.19.0 as build

WORKDIR /app
COPY ./app/package*.json ./
RUN npm install

#avoir le certificat ssl, -x509 pour certificat auto-signé, -newkey pour générer une nouvelle clé privée rsa, -nodes pour ne pas crypter la clé privée
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/ssl/private/nginx-selfsigned.key \
    -out /etc/ssl/certs/nginx-selfsigned.crt \
    -subj "/C=FR/ST=RHONE/L=LYON/O=42 lyon/OU=42/CN=127.0.0.1/UID=avaganay"

EXPOSE 8000
CMD ["npm", "run", "dev"]
