# Generated by Django 4.2.9 on 2024-03-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_profile_icon_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='icon',
        ),
    ]
