# Generated by Django 4.2.10 on 2024-02-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_profile_user_profile_user_id_tableuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='icon',
        ),
    ]
