# Generated by Django 4.2.9 on 2024-03-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_profile_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar42',
            field=models.CharField(max_length=100, null=True, verbose_name='url42'),
        ),
    ]
